- name: Install packages
  pip:
    name:
    - docker-compose
    - docker<7.0
    - requests==2.31.0

- name: Git chekout
  git:
    repo: "{{ git_repository }}"
    dest: "{{ deploymnt_path }}"
    version: "{{ git_branch }}"

- name: Run docker compose
  docker_compose:
    project_src: "{{ deployment_path }}"
    build: yes